#!/bin/bash
#SBATCH --job-name=CISM_hist
# KeyCLIM: nn9252k; INES: nn9560k; GREASE: nn8006k
#SBATCH --account=nn8006k
#SBATCH --partition=preproc
#SBATCH --time=0-00:10:00
#SBATCH --ntasks=1 --cpus-per-task=1
#SBATCH --mem-per-cpu=8G

## Setting variables and prepare runtime environment:
##----------------------------------------------------
## Recommended safety settings:
set -o errexit # Make bash exit on any error
set -o nounset # Treat unset variables as errors

module purge
module load netCDF-Fortran/4.5.2-gompi-2020a
module list  

# run 
time srun ./gpdd.x 

# Finish the script
exit 0
