#!/bin/bash
#SBATCH --job-name=gpdd
# KeyCLIM: nn9252k; INES: nn9560k; GREASE: nn8006k
#SBATCH --account=nn8006k
#SBATCH --partition=preproc
#SBATCH --time=0-01:00:00
#SBATCH --ntasks=1 --cpus-per-task=1
#SBATCH --mem-per-cpu=8G

## Setting variables and prepare runtime environment:
##----------------------------------------------------
## Recommended safety settings:
set -o errexit # Make bash exit on any error
set -o nounset # Treat unset variables as errors

module --quiet purge
module --quiet load CDO/1.9.10-gompi-2021a
module --quiet load NCO/5.0.1-foss-2021a
module list  

# run 
time srun ./scalars_basin.sh 

# Finish the script
exit 0
